import { useQuery } from '@tanstack/react-query';
import { Helmet } from 'react-helmet-async';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, MapPin } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Badge } from '@/components/ui/badge';

type DbResult = { data: unknown; error: { message: string } | null };
interface DbQuery extends PromiseLike<DbResult> { eq(column: string, value: unknown): DbQuery; single(): Promise<DbResult>; }
const database = supabase as unknown as { from(table: string): { select(columns?: string): DbQuery } };

const SITE_URL = 'https://twv-llc.com';
type Story = { user_id: string; slug: string; title: string; project_type: string; location_public: string | null; completed_on: string | null; summary: string; challenge: string | null; work_completed: string; outcomes: string | null; services: string[]; featured_image_url: string | null; article_title: string | null; article_excerpt: string | null; article_body: string | null; seo_title: string | null; seo_description: string | null; published_at: string };
type Author = { handle: string; display_name: string; bio: string | null; avatar_url: string | null };

export default function PortfolioStoryPage() {
  const { slug = '' } = useParams();
  const page = useQuery({ queryKey: ['public-portfolio-story', slug], queryFn: async () => { const entryResult = await database.from('pm_portfolio_entries').select('*').eq('slug', slug).eq('status', 'published').single(); if (entryResult.error) throw entryResult.error; const entry = entryResult.data as Story; const authorResult = await database.from('public_profiles').select('handle, display_name, bio, avatar_url').eq('user_id', entry.user_id).eq('is_public', true).single(); if (authorResult.error) throw authorResult.error; return { entry, author: authorResult.data as Author }; } });
  if (page.isLoading) return <div className="flex min-h-screen items-center justify-center">Loading case study…</div>;
  if (page.error || !page.data) return <div className="flex min-h-screen items-center justify-center p-6 text-center"><div><h1 className="text-2xl font-semibold">Case study not found</h1><p className="mt-2 text-muted-foreground">This story is unavailable or has not been published.</p></div></div>;
  const { entry, author } = page.data; const title = entry.seo_title || entry.article_title || entry.title; const description = entry.seo_description || entry.article_excerpt || entry.summary; const canonical = `${SITE_URL}/work/${entry.slug}`; const paragraphs = (entry.article_body || entry.work_completed).split(/\n{2,}/).filter(Boolean);
  const schema = { '@context': 'https://schema.org', '@type': 'Article', headline: entry.article_title || entry.title, description, image: entry.featured_image_url || undefined, datePublished: entry.published_at, author: { '@type': 'Person', name: author.display_name, url: `${SITE_URL}/professionals/${author.handle}` }, publisher: { '@type': 'Organization', name: 'TW Ventures', url: SITE_URL } };
  return <main className="min-h-screen bg-background"><Helmet><title>{title} | TW Ventures</title><meta name="description" content={description} /><meta name="robots" content="index, follow, max-image-preview:large" /><link rel="canonical" href={canonical} /><meta property="og:type" content="article" /><meta property="og:title" content={title} /><meta property="og:description" content={description} /><meta property="og:url" content={canonical} />{entry.featured_image_url && <meta property="og:image" content={entry.featured_image_url} />}<script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
    <article><header className="border-b bg-slate-950 text-white"><div className="mx-auto max-w-4xl px-6 py-16"><Link to={`/professionals/${author.handle}`} className="inline-flex items-center text-sm text-blue-300"><ArrowLeft className="mr-2 h-4 w-4" />{author.display_name}'s portfolio</Link><div className="mt-8 flex flex-wrap gap-2"><Badge className="bg-blue-500/20 text-blue-100">{entry.project_type}</Badge>{entry.services.map((service) => <Badge key={service} className="bg-white/10 text-white">{service}</Badge>)}</div><h1 className="mt-5 text-4xl font-semibold tracking-tight sm:text-5xl">{entry.article_title || entry.title}</h1><p className="mt-5 max-w-3xl text-xl leading-8 text-slate-300">{entry.article_excerpt || entry.summary}</p>{entry.location_public && <p className="mt-6 flex items-center gap-2 text-slate-400"><MapPin className="h-4 w-4" />{entry.location_public}</p>}</div></header>{entry.featured_image_url && <img src={entry.featured_image_url} alt={entry.title} className="mx-auto aspect-[16/7] w-full max-w-6xl object-cover" />}<div className="mx-auto max-w-3xl px-6 py-14"><div className="space-y-6 text-lg leading-8 text-foreground/85">{paragraphs.map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div>{entry.outcomes && <aside className="mt-12 rounded-2xl border bg-muted/30 p-6"><h2 className="text-xl font-semibold">Project outcome</h2><p className="mt-3 leading-7 text-muted-foreground">{entry.outcomes}</p></aside>}<div className="mt-14 flex items-center gap-4 border-t pt-8">{author.avatar_url && <img src={author.avatar_url} alt="" className="h-14 w-14 rounded-full object-cover" />}<div><p className="font-semibold">{author.display_name}</p>{author.bio && <p className="mt-1 text-sm text-muted-foreground">{author.bio}</p>}</div></div></div></article>
  </main>;
}
