import { useQuery } from '@tanstack/react-query';
import { Helmet } from 'react-helmet-async';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, BriefcaseBusiness, MapPin } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';

type DbResult = { data: unknown; error: { message: string } | null };
interface DbQuery extends PromiseLike<DbResult> { eq(column: string, value: unknown): DbQuery; order(column: string, options?: { ascending?: boolean }): DbQuery; single(): Promise<DbResult>; }
const database = supabase as unknown as { from(table: string): { select(columns?: string): DbQuery } };

const SITE_URL = 'https://twv-llc.com';
type Profile = { user_id: string; handle: string; display_name: string; bio: string | null; avatar_url: string | null };
type Entry = { id: string; slug: string; title: string; project_type: string; location_public: string | null; summary: string; featured_image_url: string | null; completed_on: string | null; services: string[]; article_title: string | null; article_excerpt: string | null };

export default function PublicPortfolioPage() {
  const { handle = '' } = useParams();
  const page = useQuery({ queryKey: ['public-pm-portfolio', handle], queryFn: async () => { const profileResult = await database.from('public_profiles').select('user_id, handle, display_name, bio, avatar_url').eq('handle', handle).eq('is_public', true).single(); if (profileResult.error) throw profileResult.error; const profile = profileResult.data as Profile; const entriesResult = await database.from('pm_portfolio_entries').select('id, slug, title, project_type, location_public, summary, featured_image_url, completed_on, services, article_title, article_excerpt').eq('user_id', profile.user_id).eq('status', 'published').order('published_at', { ascending: false }); if (entriesResult.error) throw entriesResult.error; return { profile, entries: (entriesResult.data ?? []) as Entry[] }; } });
  if (page.isLoading) return <div className="flex min-h-screen items-center justify-center">Loading portfolio…</div>;
  if (page.error || !page.data) return <div className="flex min-h-screen items-center justify-center p-6 text-center"><div><h1 className="text-2xl font-semibold">Portfolio not found</h1><p className="mt-2 text-muted-foreground">This professional portfolio is unavailable or private.</p></div></div>;
  const { profile, entries } = page.data; const canonical = `${SITE_URL}/professionals/${profile.handle}`; const description = profile.bio || `Explore ${profile.display_name}'s completed real estate and construction projects.`;
  return <main className="min-h-screen bg-slate-950 text-white"><Helmet><title>{profile.display_name} — Project Portfolio | TW Ventures</title><meta name="description" content={description} /><meta name="robots" content="index, follow, max-image-preview:large" /><link rel="canonical" href={canonical} /><meta property="og:title" content={`${profile.display_name} — Project Portfolio`} /><meta property="og:description" content={description} /><meta property="og:url" content={canonical} /><meta property="og:type" content="profile" /></Helmet>
    <section className="border-b border-white/10 bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950"><div className="mx-auto max-w-6xl px-6 py-20"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-blue-300">TW Ventures professional portfolio</p><div className="mt-8 flex flex-col gap-6 sm:flex-row sm:items-center">{profile.avatar_url ? <img src={profile.avatar_url} alt="" className="h-24 w-24 rounded-2xl object-cover ring-1 ring-white/20" /> : <div className="flex h-24 w-24 items-center justify-center rounded-2xl bg-blue-500/15"><BriefcaseBusiness className="h-10 w-10 text-blue-300" /></div>}<div><h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">{profile.display_name}</h1>{profile.bio && <p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">{profile.bio}</p>}</div></div></div></section>
    <section className="mx-auto max-w-6xl px-6 py-14"><div className="mb-8"><p className="text-sm font-semibold text-blue-300">Selected work</p><h2 className="mt-2 text-3xl font-semibold">Projects delivered with intention.</h2></div>{entries.length ? <div className="grid gap-6 md:grid-cols-2">{entries.map((entry) => <Link key={entry.id} to={`/work/${entry.slug}`} className="group overflow-hidden rounded-2xl border border-white/10 bg-white/5 transition hover:-translate-y-1 hover:border-blue-400/40">{entry.featured_image_url && <img src={entry.featured_image_url} alt="" className="aspect-[16/9] w-full object-cover" />}<div className="p-6"><div className="flex flex-wrap gap-2"><Badge className="border-white/15 bg-white/10 text-white">{entry.project_type}</Badge>{entry.completed_on && <Badge className="border-white/15 bg-white/10 text-white">{new Date(`${entry.completed_on}T12:00:00`).getFullYear()}</Badge>}</div><h3 className="mt-4 text-2xl font-semibold">{entry.article_title || entry.title}</h3>{entry.location_public && <p className="mt-2 flex items-center gap-2 text-sm text-slate-400"><MapPin className="h-4 w-4" />{entry.location_public}</p>}<p className="mt-4 line-clamp-3 leading-7 text-slate-300">{entry.article_excerpt || entry.summary}</p><span className="mt-5 inline-flex items-center text-sm font-semibold text-blue-300">Read case study <ArrowRight className="ml-2 h-4 w-4 transition group-hover:translate-x-1" /></span></div></Link>)}</div> : <Card className="border-white/10 bg-white/5 text-white"><CardContent className="p-10 text-center">Published work will appear here.</CardContent></Card>}</section>
  </main>;
}
