import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Save, FileText, Share2, Copy } from "lucide-react";
import { StockData, DCFScenarios, InvestmentThesis } from "./types";
import WatchlistDialog from "./WatchlistDialog";
import { toast } from "sonner";

interface ExportActionsProps {
  ticker: string;
  stockData?: StockData | null;
  dcfScenarios?: DCFScenarios;
  investmentThesis?: InvestmentThesis;
}

const reportNumber = (value: number | undefined, render: (number: number) => string) =>
  value != null && Number.isFinite(value) ? render(value) : 'N/A';

const ExportActions = ({ ticker, stockData, dcfScenarios, investmentThesis }: ExportActionsProps) => {
  const [watchlistDialogOpen, setWatchlistDialogOpen] = useState(false);
  const [exporting, setExporting] = useState(false);

  const defaultDcfScenarios: DCFScenarios = {
    low: { revenueGrowth: 5, netMargin: 8, fcfGrowth: 3, exitMultiple: 15, discountRate: 12 },
    base: { revenueGrowth: 12, netMargin: 15, fcfGrowth: 8, exitMultiple: 20, discountRate: 10 },
    high: { revenueGrowth: 20, netMargin: 22, fcfGrowth: 15, exitMultiple: 25, discountRate: 8 }
  };

  const defaultInvestmentThesis: InvestmentThesis = {
    moat: "",
    risks: "",
    opportunities: ""
  };

  const generateReportContent = () => {
    if (!stockData) return "";
    
    const currentDate = new Date().toLocaleDateString();
    const reportData = dcfScenarios || defaultDcfScenarios;
    const thesis = investmentThesis || defaultInvestmentThesis;
    
    return `
# ${ticker} Investment Analysis Report
Generated on ${currentDate}

## Company Overview
- **Symbol**: ${ticker}
- **Company**: ${stockData.companyName || `${ticker} Corporation`}
- **Current Price**: ${reportNumber(stockData.price, value => `$${value.toFixed(2)}`)}
- **Market Cap**: ${reportNumber(stockData.marketCap, value => `$${(value / 1e9).toFixed(1)}B`)}
- **P/E Ratio**: ${reportNumber(stockData.pe, value => value.toFixed(1))}
- **Sector**: ${stockData.sector || 'N/A'}

## Financial Metrics
- **ROE**: ${reportNumber(stockData.roe, value => `${(value * 100).toFixed(1)}%`)}
- **Debt to Equity**: ${reportNumber(stockData.debtToEquity, value => value.toFixed(2))}
- **Current Ratio**: ${reportNumber(stockData.currentRatio, value => value.toFixed(2))}
- **Dividend Yield**: ${reportNumber(stockData.dividendYield, value => `${(value * 100).toFixed(1)}%`)}
- **Beta**: ${reportNumber(stockData.beta, value => value.toFixed(2))}

## DCF Analysis
### Base Case Scenario
- Revenue Growth: ${reportData.base.revenueGrowth}%
- Net Margin: ${reportData.base.netMargin}%
- FCF Growth: ${reportData.base.fcfGrowth}%
- Exit Multiple: ${reportData.base.exitMultiple}x
- Discount Rate: ${reportData.base.discountRate}%

## Investment Thesis
### Economic Moat & Competitive Advantages
${thesis.moat || 'Not specified'}

### Key Risks & Concerns
${thesis.risks || 'Not specified'}

### Growth Opportunities
${thesis.opportunities || 'Not specified'}

---
*Report generated by SomaTech Investment Analysis Platform*
    `.trim();
  };

  const exportToPDF = async () => {
    if (!stockData) {
      toast.error('No stock data available to export');
      return;
    }

    setExporting(true);
    try {
      const content = generateReportContent();
      
      // Create a same-origin print window, then use textContent for all report
      // data. User-authored thesis text must never be interpreted as markup.
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.opener = null;
        printWindow.document.title = `${ticker} Investment Analysis Report`;
        const style = printWindow.document.createElement('style');
        style.textContent = 'body{font-family:Arial,sans-serif;margin:40px;line-height:1.6}pre{white-space:pre-wrap;font-family:Arial,sans-serif}@media print{body{margin:20px}}';
        const report = printWindow.document.createElement('pre');
        report.textContent = content;
        printWindow.document.head.appendChild(style);
        printWindow.document.body.replaceChildren(report);
        printWindow.document.close();
        
        // Wait for content to load, then trigger print
        setTimeout(() => {
          printWindow.print();
          printWindow.close();
        }, 500);
        
        toast.success(`${ticker} report ready for printing/PDF export`);
      } else {
        toast.error('Allow pop-ups to print or save this report as a PDF');
      }
    } catch (error) {
      console.error('Export error:', error);
      toast.error('Failed to export report');
    } finally {
      setExporting(false);
    }
  };

  const copyToClipboard = async () => {
    if (!stockData) {
      toast.error('No stock data available to copy');
      return;
    }

    try {
      const content = generateReportContent();
      await navigator.clipboard.writeText(content);
      toast.success(`${ticker} analysis copied to clipboard`);
    } catch (error) {
      console.error('Copy error:', error);
      toast.error('Failed to copy to clipboard');
    }
  };

  const shareAnalysis = async () => {
    if (!stockData) {
      toast.error('No stock data available to share');
      return;
    }

    try {
      const shareData = {
        title: `${ticker} Investment Analysis`,
        text: `Check out my ${ticker} investment analysis on SomaTech`,
        url: window.location.href
      };

      if (navigator.share) {
        await navigator.share(shareData);
        toast.success('Analysis shared successfully');
      } else {
        // Fallback: copy URL to clipboard
        await navigator.clipboard.writeText(shareData.url);
        toast.success('Analysis URL copied to clipboard');
      }
    } catch (error) {
      console.error('Share error:', error);
      toast.error('Failed to share analysis');
    }
  };

  return (
    <>
      <Card className="border-0 shadow-lg bg-gradient-to-br from-white to-gray-50 dark:from-gray-900 dark:to-gray-800">
        <CardHeader className="pb-4">
          <CardTitle className="text-xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            Export & Share {ticker} Analysis
          </CardTitle>
          <CardDescription className="text-gray-600 dark:text-gray-400">
            Save your analysis, export reports, or share insights with others
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Primary Actions */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <Button 
              onClick={exportToPDF}
              disabled={!stockData || exporting}
              className="h-12 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg hover:shadow-xl transition-all duration-200 transform hover:scale-105"
            >
              <FileText className="h-4 w-4 mr-2" />
              {exporting ? "Generating..." : "Export PDF Report"}
            </Button>
            <Button 
              variant="outline" 
              onClick={() => setWatchlistDialogOpen(true)}
              disabled={!stockData}
              className="h-12 border-2 border-gray-200 hover:border-blue-300 hover:bg-blue-50 dark:border-gray-700 dark:hover:border-blue-600 dark:hover:bg-blue-950 transition-all duration-200"
            >
              <Save className="h-4 w-4 mr-2" />
              Save to Watchlist
            </Button>
          </div>
          
          {/* Secondary Actions */}
          <div className="grid grid-cols-2 gap-3">
            <Button 
              variant="outline"
              onClick={copyToClipboard}
              disabled={!stockData}
              className="h-10 border-gray-200 hover:border-gray-300 hover:bg-gray-50 dark:border-gray-700 dark:hover:border-gray-600 dark:hover:bg-gray-800 transition-all duration-200"
            >
              <Copy className="h-4 w-4 mr-2" />
              Copy Text
            </Button>
            <Button 
              variant="outline"
              onClick={shareAnalysis}
              disabled={!stockData}
              className="h-10 border-gray-200 hover:border-gray-300 hover:bg-gray-50 dark:border-gray-700 dark:hover:border-gray-600 dark:hover:bg-gray-800 transition-all duration-200"
            >
              <Share2 className="h-4 w-4 mr-2" />
              Share
            </Button>
          </div>
          
          {/* Status Indicator */}
          {stockData && (
            <div className="flex items-center space-x-2 text-sm text-accent dark:text-accent">
              <div className="w-2 h-2 bg-accent rounded-full animate-pulse"></div>
              <span>Analysis ready for export</span>
            </div>
          )}
        </CardContent>
      </Card>

      <WatchlistDialog
        open={watchlistDialogOpen}
        onOpenChange={setWatchlistDialogOpen}
        ticker={ticker}
        stockData={stockData ?? null}
        dcfScenarios={dcfScenarios || defaultDcfScenarios}
        investmentThesis={investmentThesis || defaultInvestmentThesis}
      />
    </>
  );
};

export default ExportActions;
