import { useMemo, useState } from 'react';
import { Bar, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, AlertTriangle, CheckCircle2, Info, TrendingDown, TrendingUp } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import type { StockData } from './types';
import DataSourceTag from './DataSourceTag';
import { SOURCE_NAMES } from '@/lib/provenance';
import { AXIS_PROPS, CHART_COLORS, GRID_PROPS, TOOLTIP_STYLE } from '@/lib/chartTheme';
import { buildStatementKpis, buildStatementSignals, buildTtmPeriod, derivedFreeCashFlow, money, normalizeAnnual, ratio, totalDebt, type AnnualFinancial, type StatementKind, type StatementKpi } from './financialStatementAnalytics';
import { buildAnalyticalRatios, buildQualityChecks } from './financialStatementQuality';

type Metric = { key: keyof AnnualFinancial; label: string; derived?: boolean };
const INCOME: Metric[] = [{ key: 'revenue', label: 'Revenue' }, { key: 'grossProfit', label: 'Gross Profit' }, { key: 'researchAndDevelopment', label: 'Research & Development' }, { key: 'sellingGeneralAdministrative', label: 'SG&A' }, { key: 'operatingIncome', label: 'Operating Income' }, { key: 'interestExpense', label: 'Interest Expense' }, { key: 'pretaxIncome', label: 'Pretax Income' }, { key: 'incomeTaxExpense', label: 'Income Tax' }, { key: 'netIncome', label: 'Net Income' }];
const BALANCE: Metric[] = [{ key: 'cash', label: 'Cash & Equivalents' }, { key: 'receivables', label: 'Receivables' }, { key: 'inventory', label: 'Inventory' }, { key: 'currentAssets', label: 'Current Assets' }, { key: 'goodwill', label: 'Goodwill' }, { key: 'totalAssets', label: 'Total Assets' }, { key: 'currentLiabilities', label: 'Current Liabilities' }, { key: 'longTermDebt', label: 'Long-term Debt' }, { key: 'shortTermDebt', label: 'Short-term Debt' }, { key: 'totalLiabilities', label: 'Total Liabilities' }, { key: 'retainedEarnings', label: 'Retained Earnings' }, { key: 'shareholderEquity', label: 'Shareholder Equity' }];
const CASH_FLOW: Metric[] = [{ key: 'netIncome', label: 'Net Income' }, { key: 'depreciationAmortization', label: 'Depreciation & Amortization' }, { key: 'stockCompensation', label: 'Stock Compensation' }, { key: 'operatingCashFlow', label: 'Operating Cash Flow' }, { key: 'capex', label: 'Capital Expenditure' }, { key: 'freeCashFlow', label: 'Free Cash Flow', derived: true }, { key: 'acquisitions', label: 'Acquisitions' }, { key: 'shareRepurchases', label: 'Share Repurchases' }, { key: 'dividendsPaid', label: 'Dividends Paid' }, { key: 'debtIssuance', label: 'Debt Issuance' }, { key: 'debtRepayment', label: 'Debt Repayment' }];

const percent = (value: number | null | undefined, digits = 1) => value == null || !Number.isFinite(value) ? '—' : `${(value * 100).toFixed(digits)}%`;
const periodLabel = (period: AnnualFinancial) => period.periodType === 'ttm'
  ? `TTM Q${period.fiscalQuarter} FY${period.fiscalYear}`
  : period.fiscalQuarter ? `Q${period.fiscalQuarter} FY${period.fiscalYear}` : `FY${period.fiscalYear}`;

function StatementTable({ annual, metrics }: { annual: AnnualFinancial[]; metrics: Metric[] }) {
  const metricValue = (period: AnnualFinancial, metric: Metric) =>
    metric.key === 'freeCashFlow' ? derivedFreeCashFlow(period) : period[metric.key] as number | null;
  return <div className="overflow-x-auto rounded-xl border border-border/50"><table className="w-full min-w-[680px] text-xs sm:text-sm"><thead><tr className="border-b bg-muted/30"><th className="sticky left-0 bg-muted px-3 py-3 text-left font-medium">Metric</th>{annual.map(period => <th key={`${period.fiscalYear}-${period.periodEnd}`} className="min-w-[105px] px-3 py-3 text-right font-medium"><span className="block">{periodLabel(period)}</span><span className="text-[9px] font-normal uppercase tracking-wide text-muted-foreground">{period.periodType === 'ttm' ? 'Derived' : period.derivation === 'mixed' ? 'Filed + derived' : 'Filed'}</span></th>)}</tr></thead><tbody>{metrics.map(metric => <tr key={metric.key} className="border-b last:border-0 hover:bg-muted/20"><td className="sticky left-0 bg-background px-3 py-3 font-medium"><span className="inline-flex items-center gap-1.5">{metric.label}{metric.derived && <DataSourceTag kind="model" />}</span></td>{annual.map(period => { const source = period.provenance?.[String(metric.key)]; const audit = source ? [source.classification, source.concept, source.form, source.filed, source.accession, source.formula].filter(Boolean).join(' · ') : 'Source metadata unavailable'; const isDerived = source?.classification === 'derived';
                    return <td key={`${period.fiscalYear}-${period.periodEnd}`} className="px-3 py-3 text-right tabular-nums"><button type="button" className={`cursor-help border-b ${isDerived ? 'border-dashed border-amber-500/60 text-amber-700 dark:text-amber-400' : 'border-dotted border-muted-foreground/40'}`} title={audit} aria-label={`${metric.label}, ${periodLabel(period)}: ${money(metricValue(period, metric))}. ${isDerived ? 'Derived, not filed. ' : ''}${audit}`}>{money(metricValue(period, metric))}{isDerived && <span aria-hidden="true" className="ml-0.5 align-super text-[8px]">ƒ</span>}</button></td>; })}</tr>)}</tbody></table></div>;
}

function KpiCard({ kpi }: { kpi: StatementKpi }) {
  const display = kpi.format === 'money' ? money(kpi.value) : kpi.format === 'percent' ? percent(kpi.value) : kpi.value == null ? '—' : `${kpi.value.toFixed(2)}×`;
  const hasChange = kpi.change != null && Number.isFinite(kpi.change);
  const ChangeIcon = hasChange && kpi.change! < 0 ? TrendingDown : TrendingUp;
  return <div className="rounded-2xl border border-border/50 bg-card/70 p-3.5"><p className="text-xs text-muted-foreground">{kpi.label}</p><div className="mt-1 flex flex-wrap items-end gap-2"><p className="text-xl font-semibold tabular-nums sm:text-2xl">{display}</p>{hasChange && <Badge variant="outline" className="mb-0.5 gap-1 text-[10px]"><ChangeIcon className="h-3 w-3" />{kpi.change! >= 0 ? '+' : ''}{percent(kpi.change)}</Badge>}</div><p className="mt-1 text-[10px] text-muted-foreground">{hasChange ? `YoY · ${kpi.detail}` : kpi.detail}</p></div>;
}

function Signals({ kind, annual }: { kind: StatementKind; annual: AnnualFinancial[] }) {
  return <div className="rounded-2xl border border-border/50 bg-card/50 p-4"><div className="mb-3 flex items-center gap-2"><Activity className="h-4 w-4 text-primary" /><h3 className="text-sm font-semibold">What changed</h3><Badge variant="outline" className="ml-auto text-[10px]">Deterministic</Badge></div><div className="grid gap-2 sm:grid-cols-2">{buildStatementSignals(kind, annual).map(signal => { const Icon = signal.tone === 'positive' ? CheckCircle2 : signal.tone === 'caution' ? AlertTriangle : Info; return <div key={signal.label} className="flex gap-2.5 rounded-xl bg-muted/35 p-3"><Icon className={`mt-0.5 h-4 w-4 shrink-0 ${signal.tone === 'positive' ? 'text-emerald-500' : signal.tone === 'caution' ? 'text-amber-500' : 'text-primary'}`} /><div><p className="text-xs font-medium">{signal.label}</p><p className="mt-0.5 text-[11px] leading-relaxed text-muted-foreground">{signal.detail}</p></div></div>; })}</div></div>;
}

function ChartShell({ title, subtitle, action, children }: { title: string; subtitle: string; action?: React.ReactNode; children: React.ReactNode }) {
  return <div className="rounded-2xl border border-border/50 bg-card/50 p-4"><div className="mb-2 flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{title}</h3><p className="text-[11px] text-muted-foreground">{subtitle}</p></div>{action}</div>{children}</div>;
}

function QualityPanel({ periods }: { periods: AnnualFinancial[] }) {
  const checks = buildQualityChecks(periods);
  const ratios = periods[0] ? buildAnalyticalRatios(periods[0]) : null;
  return <div className="grid gap-3 lg:grid-cols-2"><div className="rounded-2xl border border-border/50 p-4"><h3 className="text-sm font-semibold">Data quality</h3><div className="mt-3 space-y-2">{checks.map(check => <div key={check.label} className="flex items-start gap-2 text-xs"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${check.status === 'pass' ? 'bg-emerald-500' : check.status === 'warning' ? 'bg-amber-500' : 'bg-muted-foreground'}`} /><div><span className="font-medium">{check.label}</span><p className="text-muted-foreground">{check.detail}</p></div></div>)}</div></div><div className="rounded-2xl border border-border/50 p-4"><h3 className="text-sm font-semibold">Common-size & returns</h3><div className="mt-3 grid grid-cols-2 gap-2">{ratios && Object.entries(ratios).map(([key, value]) => <div key={key} className="rounded-lg bg-muted/30 p-2"><p className="text-[10px] capitalize text-muted-foreground">{key.replace(/([A-Z])/g, ' $1')}</p><p className="text-sm font-medium tabular-nums">{value == null ? '—' : key === 'currentRatio' || key === 'cashConversion' ? `${value.toFixed(2)}×` : percent(value)}</p></div>)}</div></div></div>;
}

function IncomeChart({ annual }: { annual: AnnualFinancial[] }) {
  const [mode, setMode] = useState<'dollars' | 'margins'>('dollars');
  const data = useMemo(() => [...annual].reverse().map(p => ({ year: periodLabel(p), revenue: p.revenue, grossProfit: p.grossProfit, operatingIncome: p.operatingIncome, netIncome: p.netIncome, grossMargin: ratio(p.grossProfit, p.revenue), operatingMargin: ratio(p.operatingIncome, p.revenue), netMargin: ratio(p.netIncome, p.revenue) })), [annual]);
  return <ChartShell title="Revenue and profitability" subtitle={mode === 'dollars' ? 'Filed annual dollars' : 'Profit as a share of revenue'} action={<div className="flex rounded-lg bg-muted p-0.5"><Button size="sm" variant={mode === 'dollars' ? 'default' : 'ghost'} className="h-7 px-2 text-[10px]" onClick={() => setMode('dollars')}>Dollars</Button><Button size="sm" variant={mode === 'margins' ? 'default' : 'ghost'} className="h-7 px-2 text-[10px]" onClick={() => setMode('margins')}>Margins</Button></div>}><ResponsiveContainer width="100%" height={290}><ComposedChart data={data} margin={{ top: 10, right: 8, left: 4, bottom: 0 }}><CartesianGrid {...GRID_PROPS} /><XAxis dataKey="year" {...AXIS_PROPS} /><YAxis {...AXIS_PROPS} tickFormatter={mode === 'dollars' ? (v: number) => money(v, 0) : (v: number) => percent(v, 0)} width={58} /><Tooltip {...TOOLTIP_STYLE} formatter={(value: number, name: string) => [mode === 'dollars' ? money(value) : percent(value), name]} /><Legend wrapperStyle={{ fontSize: 11 }} />{mode === 'dollars' ? <><Bar dataKey="revenue" name="Revenue" fill={CHART_COLORS.primary} radius={[4, 4, 0, 0]} /><Line dataKey="grossProfit" name="Gross profit" stroke={CHART_COLORS.success} strokeWidth={2} dot={false} /><Line dataKey="operatingIncome" name="Operating income" stroke={CHART_COLORS.warning} strokeWidth={2} dot={false} /><Line dataKey="netIncome" name="Net income" stroke={CHART_COLORS.purple} strokeWidth={2} dot={false} /></> : <><Line dataKey="grossMargin" name="Gross margin" stroke={CHART_COLORS.success} strokeWidth={2} /><Line dataKey="operatingMargin" name="Operating margin" stroke={CHART_COLORS.warning} strokeWidth={2} /><Line dataKey="netMargin" name="Net margin" stroke={CHART_COLORS.purple} strokeWidth={2} /></>}</ComposedChart></ResponsiveContainer></ChartShell>;
}

function BalanceChart({ annual }: { annual: AnnualFinancial[] }) {
  const data = useMemo(() => [...annual].reverse().map(p => ({ year: periodLabel(p), assets: p.totalAssets, equity: p.shareholderEquity, debt: totalDebt(p), cash: p.cash })), [annual]);
  return <ChartShell title="Capital structure" subtitle="Filed position at each fiscal year end"><ResponsiveContainer width="100%" height={290}><ComposedChart data={data} margin={{ top: 10, right: 8, left: 4, bottom: 0 }}><CartesianGrid {...GRID_PROPS} /><XAxis dataKey="year" {...AXIS_PROPS} /><YAxis {...AXIS_PROPS} tickFormatter={(v: number) => money(v, 0)} width={58} /><Tooltip {...TOOLTIP_STYLE} formatter={(value: number, name: string) => [money(value), name]} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="debt" name="Total debt" fill={CHART_COLORS.warning} radius={[4, 4, 0, 0]} /><Bar dataKey="cash" name="Cash" fill={CHART_COLORS.success} radius={[4, 4, 0, 0]} /><Line dataKey="assets" name="Total assets" stroke={CHART_COLORS.primary} strokeWidth={2} dot={false} /><Line dataKey="equity" name="Equity" stroke={CHART_COLORS.purple} strokeWidth={2} dot={false} /></ComposedChart></ResponsiveContainer></ChartShell>;
}

function CashFlowChart({ annual }: { annual: AnnualFinancial[] }) {
  const data = useMemo(() => [...annual].reverse().map(p => ({ year: periodLabel(p), operatingCashFlow: p.operatingCashFlow, freeCashFlow: derivedFreeCashFlow(p), capex: p.capex, netIncome: p.netIncome })), [annual]);
  return <ChartShell title="Cash generation and reinvestment" subtitle="Free cash flow is operating cash flow minus capital expenditure"><ResponsiveContainer width="100%" height={290}><ComposedChart data={data} margin={{ top: 10, right: 8, left: 4, bottom: 0 }}><CartesianGrid {...GRID_PROPS} /><XAxis dataKey="year" {...AXIS_PROPS} /><YAxis {...AXIS_PROPS} tickFormatter={(v: number) => money(v, 0)} width={58} /><Tooltip {...TOOLTIP_STYLE} formatter={(value: number, name: string) => [money(value), name]} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="operatingCashFlow" name="Operating cash flow" fill={CHART_COLORS.primary} radius={[4, 4, 0, 0]} /><Bar dataKey="freeCashFlow" name="Free cash flow" fill={CHART_COLORS.success} radius={[4, 4, 0, 0]} /><Bar dataKey="capex" name="Capex" fill={CHART_COLORS.warning} radius={[4, 4, 0, 0]} /><Line dataKey="netIncome" name="Net income" stroke={CHART_COLORS.purple} strokeWidth={2} dot={false} /></ComposedChart></ResponsiveContainer></ChartShell>;
}

function StatementPanel({ kind, annual, quarterly, metrics }: { kind: StatementKind; annual: AnnualFinancial[]; quarterly: AnnualFinancial[]; metrics: Metric[] }) {
  const [periodMode, setPeriodMode] = useState<'annual' | 'quarterly' | 'aggregate'>('annual');
  const ttm = useMemo(() => [buildTtmPeriod(quarterly), buildTtmPeriod(quarterly.slice(4))].filter(Boolean) as AnnualFinancial[], [quarterly]);
  const latestQuarter = quarterly[0];
  const priorYearQuarter = latestQuarter?.fiscalQuarter == null ? undefined : quarterly.find(period => period.fiscalYear === latestQuarter.fiscalYear - 1 && period.fiscalQuarter === latestQuarter.fiscalQuarter);
  const latestBalance = [latestQuarter, priorYearQuarter].filter(Boolean) as AnnualFinancial[];
  const periods = periodMode === 'annual' ? annual : periodMode === 'quarterly' ? quarterly : kind === 'balance' ? latestBalance : ttm;
  const kpis = buildStatementKpis(kind, periods);
  const aggregateLabel = kind === 'balance' ? 'Latest' : 'TTM';
  return <div className="space-y-4"><div className="flex justify-end"><div className="flex rounded-lg bg-muted p-0.5">{(['annual', 'quarterly', 'aggregate'] as const).map(mode => <Button key={mode} size="sm" variant={periodMode === mode ? 'default' : 'ghost'} className="h-7 px-3 text-[10px]" onClick={() => setPeriodMode(mode)}>{mode === 'annual' ? 'Annual' : mode === 'quarterly' ? 'Quarterly' : aggregateLabel}</Button>)}</div></div>{periods.length ? <><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{kpis.map(kpi => <KpiCard key={kpi.label} kpi={kpi} />)}</div>{kind === 'income' ? <IncomeChart annual={periods} /> : kind === 'balance' ? <BalanceChart annual={periods} /> : <CashFlowChart annual={periods} />}<Signals kind={kind} annual={periods} /><QualityPanel periods={periods} /><div><div className="mb-2 flex items-center justify-between"><div><h3 className="text-sm font-semibold">{periodMode === 'annual' ? 'Filed statement' : periodMode === 'quarterly' ? 'Quarterly statement' : aggregateLabel}</h3><p className="text-[11px] text-muted-foreground">Filed values remain distinct from derived quarter and TTM calculations. A figure marked <span className="border-b border-dashed border-amber-500/60 text-amber-700 dark:text-amber-400">ƒ</span> was recovered from an accounting identity because the filer tagged no concept for it; hover any figure for its source.</p></div><DataSourceTag kind={periodMode === 'annual' ? 'filed' : 'model'} /></div><StatementTable annual={periods} metrics={metrics} /></div></> : <div className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">A complete set of SEC facts is unavailable for this view.</div>}</div>;
}

interface FinancialStatementsProps { ticker: string; stockData?: StockData | null }
const FinancialStatements = ({ ticker, stockData }: FinancialStatementsProps) => {
  const annual = useMemo(() => normalizeAnnual(stockData?.annualFinancials ?? []), [stockData?.annualFinancials]);
  const quarterly = useMemo(() => normalizeAnnual(stockData?.quarterlyFinancials ?? []), [stockData?.quarterlyFinancials]);
  return <Card className="w-full"><CardHeader className="p-4 sm:p-6"><CardTitle className="flex items-center gap-2 text-lg sm:text-xl">{ticker} Financial Statements <DataSourceTag kind="filed" /></CardTitle><CardDescription>Top-down analysis of annual and quarterly SEC filings. Derived standalone quarters and TTM values are labeled; incomplete facts remain unavailable.</CardDescription></CardHeader><CardContent className="p-4 pt-0 sm:p-6 sm:pt-0">{annual.length === 0 ? <p className="text-sm text-muted-foreground">No annual filing data is available for this ticker in {SOURCE_NAMES.filingSystem}.</p> : <Tabs defaultValue="income" className="w-full"><TabsList className="grid h-auto w-full grid-cols-3"><TabsTrigger value="income">Income</TabsTrigger><TabsTrigger value="balance">Balance</TabsTrigger><TabsTrigger value="cashflow">Cash Flow</TabsTrigger></TabsList><TabsContent value="income" className="mt-5"><StatementPanel kind="income" annual={annual} quarterly={quarterly} metrics={INCOME} /></TabsContent><TabsContent value="balance" className="mt-5"><StatementPanel kind="balance" annual={annual} quarterly={quarterly} metrics={BALANCE} /></TabsContent><TabsContent value="cashflow" className="mt-5"><StatementPanel kind="cashflow" annual={annual} quarterly={quarterly} metrics={CASH_FLOW} /></TabsContent></Tabs>}</CardContent></Card>;
};
export default FinancialStatements;
