// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Supabase browser client.
 *
 * The placeholder fallback below exists ONLY so unit tests and local tooling can
 * import this module without a configured environment. It must never reach a
 * real user: a build that silently ships `placeholder.supabase.co` looks
 * healthy, deploys clean, and then fails on every sign-in with
 * ERR_NAME_NOT_RESOLVED — which is exactly how production auth broke.
 *
 * So: in a production build, missing configuration is a hard failure at module
 * load, loud and immediate, rather than a 404 on a domain that does not exist.
 */
const PLACEHOLDER_URL = 'https://placeholder.supabase.co';
const PLACEHOLDER_KEY = 'placeholder-anon-key';

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

const isConfigured = Boolean(rawUrl && rawKey);

// `MODE === 'test'` covers Vitest; DEV covers `vite dev`.
const isTestOrDev = import.meta.env.MODE === 'test' || import.meta.env.DEV;

if (!isConfigured) {
  const message =
    'Supabase is not configured: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are missing. ' +
    'Authentication, portfolios and every persisted feature will fail. ' +
    'These are inlined at BUILD time, so they must be set on the machine that runs ' +
    '`npm run build` — copy .env.example to .env and fill them in, then rebuild ' +
    'and re-upload dist/.';

  if (isTestOrDev) {
    console.warn(`[supabase] ${message} Falling back to placeholder values for local/test execution.`);
  } else {
    // Production: refuse to pretend. Surfaces in the build log and, if it ever
    // reaches a browser, in the console on first import rather than mid-login.
    throw new Error(`[supabase] ${message}`);
  }
}

export const supabase = createClient<Database>(
  rawUrl || PLACEHOLDER_URL,
  rawKey || PLACEHOLDER_KEY,
  {
    auth: {
      storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);

/** True when real credentials were supplied — useful for gating UI on config. */
export const isSupabaseConfigured = isConfigured;
