const e = (value: unknown) => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c] as string));
export default async function handler(_req: any, res: any) {
  const base = process.env.VITE_SUPABASE_URL; const key = process.env.VITE_SUPABASE_ANON_KEY;
  if (!base || !key) return res.status(503).send('Research is temporarily unavailable');
  const response = await fetch(`${base}/rest/v1/public_research_posts?select=slug,ticker,company_name,title,summary,published_at&order=published_at.desc&limit=50`, { headers: { apikey: key, Authorization: `Bearer ${key}` } });
  if (!response.ok) return res.status(503).send('Research is temporarily unavailable');
  const posts = await response.json();
  res.setHeader('Content-Type','text/html; charset=utf-8'); res.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=86400');
  res.send(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Community Investment Research | SomaTech</title><meta name="description" content="Source-aware investment analysis shared by the SomaTech community."><link rel="canonical" href="https://somatech.pro/research"><meta name="robots" content="index,follow"><style>body{margin:0;background:#f7f8fb;color:#161923;font:16px/1.6 Inter,system-ui}main{max-width:900px;margin:auto;padding:48px 20px}a{color:inherit;text-decoration:none}.brand{color:#2463eb;font-weight:800}.grid{display:grid;gap:16px}.card{display:block;background:white;border:1px solid #dde2ea;border-radius:16px;padding:22px}.card:hover{border-color:#2463eb}h1{font-size:42px;line-height:1.1}.ticker{color:#2463eb;font-weight:700;font-size:12px;letter-spacing:.08em}.summary{color:#596174}</style></head><body><main><a class="brand" href="https://somatech.pro">SomaTech</a><h1>Community Investment Research</h1><p>Independent, source-aware analysis with explicit risks, assumptions, and disclosures.</p><div class="grid">${posts.length ? posts.map((p:any)=>`<a class="card" href="/research/${e(p.slug)}"><span class="ticker">${e(p.ticker)} · ${e(p.company_name)}</span><h2>${e(p.title)}</h2><p class="summary">${e(p.summary)}</p></a>`).join('') : '<div class="card"><h2>Research is being prepared</h2><p>Published community analysis will appear here.</p></div>'}</div></main></body></html>`);
}
